version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: simple-payments-app
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: simple-payments-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: simple_payments
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
