version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    networks:
     - app-network
    container_name: simple-payments-app
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: simple-payments-db
    networks:
        - app-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: simple_payments
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    networks:
        - app-network
    ports:
        - "8000:80"
    volumes:
        - .:/var/www
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
networks:
 app-network:
   driver: bridge

volumes:
  dbdata:
